builds:
  - binary: yj
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
    - CGO_ENABLED=0
archive:
  format: binary
  name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
 name_template: 'checksums.txt'
snapshot:
 name_template: "{{ .Tag }}-next"
